### ISSUE TITLE
Empty Instagram link

### ISSUE THREAD

**Issue by josefaidt** [kylemmancuso/DreamLANs-Consulting#2]
Should I remove the empty instagram link? Any other social links you may want to add?
- Github
- Spiceworks
- MSDN

These are just random suggestions. Also, not sure if you have an icon logo, but that would be useful as a favicon

**Comment by Acoust1cReverb** [comment]
I don't care for the instagram link for now. If we could hide it for now, I'm good with that. We can put a gihub link, but I don't see that it's really necessary.

**Comment by josefaidt** [comment]
fixed via PR #5
